music_website/home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    #path('my_collections/<int:user_id>', views.collections_index, name='collections_index'),
    path('', views.home_index, name='home_index'),
    path('register', views.register, name="register"),
    path('search', views.search, name="search"),
    path('search/<int:collection_id>', views.search, name="search"),
    path('artist/<int:artist_id>', views.artist, name='artist'),
    path('record/<int:record_id>', views.record, name='record'),
    path('artist/save/d/<int:discogs_id>', views.discogs_save_artist, name='discogs_save_artist'),
    path('record/save/d/<str:discogs_master_id>', views.discogs_save_record, name='discogs_save_record'),
    path('artist/<int:artist_id>/like', views.save_like_artist, name='like_artist'),
    path('artist/<int:artist_id>/unlike', views.save_unlike_artist, name='unlike_artist'),
    path('review', views.review, name='review'),
    path('review/<int:review_id>', views.review, name='review'),
    path('review/<int:review_id>/view', views.review_view, name='review_view'),
    path('reviews', views.reviews, name='reviews'),
    path('mycollections/<str:username>', views.mycollections, name='mycollections'),
    path('mycollections/<str:username>/new_collection', views.new_collection_form, name='new_collection_form'),
    path('mycollections/<str:username>/save_collection', views.save_new_collection, name='save_new_collection'),
    path('mycollections/<str:username>/<int:collection_id>', views.single_collection, name='single_collection'),
    path('mycollections/<int:collection_id>/delete', views.delete_collection, name='delete_collection'),
    #path('mycollections/<str:username>/<int:collection_id>/add_new_record', views.add_to_collection, name='add_to_collection'),
    path('myartists', views.my_artists, name='myartists'),
    path('staffpick', views.staff_picks, name='staff_picks'),
    path('staffpick/<int:pick_id>', views.staff_pick_edit, name='staff_pick'),
    path('staffpick/<int:pick_id>/view', views.staff_pick_view, name='staff_pick_view'),
    path('staffpick/<int:pick_id>/delete', views.staff_pick_delete, name='staff_pick_delete'),
    path('record/<int:record_id>/staffpick', views.staff_pick_add, name='staff_pick_add'),
    path('add_to_collection/<int:record_id>', views.add_to_collection, name='add_to_collection'),
    path('add_to_collection/<int:record_id>/save', views.add_to_collection_save, name='add_to_collection_save'),
    path('remove_from_collection/<int:collection_id>/<int:record_id>', views.remove_from_collection, name='remove_from_collection'),

]

music_website/music_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('collection/', include('collection.urls'))
]

music_website/home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
    """ Extending the User Creation form base from Django
    See https://docs.djangoproject.com/en/1.8/_modules/django/contrib/auth/forms/#UserCreationForm
    and https://docs.djangoproject.com/en/3.2/topics/auth/default/#django.contrib.auth.forms.UserCreationForm
    """
    email = forms.EmailField(max_length=254,required=True, help_text="Please provide a valid email address we can use to contact you.")
    first_name = forms.CharField(max_length=150, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=150, required=False, help_text='Optional.')

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2", "first_name", "last_name")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user

music_website/home/views.py
from django import http
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from home.models import Artist, Rating, Record, Like_Artist, Collection, Collection_Record, Staff_Picks
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from home import discogs
from .forms import NewUserForm
from django.contrib import messages
from home.search import Search
from django.urls import reverse
from home import discogs2db
from django.utils import timezone
from django.db.models import Avg, Count
from django.core.paginator import Paginator
from django.db import IntegrityError


def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("/")
        messages.error(
            request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request=request, template_name="registration/register.html", context={"form": form})


def home_index(request):
    top_artists = Artist.objects.annotate(avg_rating=Avg('record__rating__rating'), review_count=Count(
        'record__rating'), likes=Count('like_artist')).order_by('-avg_rating', '-review_count')[:5]
    # .exclude(avg_rating=None) # se quisermos excluir artistas sem ratings

    top_records = Record.objects.annotate(avg_rating=Avg('rating__rating'), review_count=Count(
        'rating')).order_by('-avg_rating', '-review_count')[:5]

    top_reviews = Rating.objects.order_by('-creation_date')[:3]

    staff_picks = Staff_Picks.objects.annotate(avg_rating=Avg('record__rating__rating'), review_count=Count(
        'record__rating')).order_by('-creation_date')[:3]

    context = {
        "top_artists": top_artists,
        "top_records": top_records,
        "top_reviews": top_reviews,
        "staff_picks": staff_picks,
    }
    return render(request, "index.html", context=context)


def search(request, collection_id=None):
    context = {}
    if request.method == "POST" and request.POST["query"]:
        context["query"] = request.POST["query"]
        res = Search().search(request.POST["query"])
        context["results"] = res
    context['collection_id'] = collection_id
    return render(request, "search.html", context=context)


def discogs_save_artist(request, discogs_id):
    print(f"Saving discogs artist {discogs_id} to database...")
    artist_id = discogs2db.save_artist_to_db(discogs_id)
    return HttpResponseRedirect(reverse('home:artist', args=(artist_id,)))


def discogs_save_record(request, discogs_master_id):
    print(f"Saving discogs record {discogs_master_id} to database...")
    record_id = discogs2db.save_record_to_db(discogs_master_id)
    return HttpResponseRedirect(reverse('home:record', args=(record_id,)))


@login_required
def save_like_artist(request, artist_id):
    try:
        Like_Artist.objects.create(
            user_id_id=request.user.id, artist_id_id=artist_id, like=True)
    finally:
        return HttpResponseRedirect(reverse('home:artist', args=(artist_id,)))


@login_required
def save_unlike_artist(request, artist_id):
    try:
        Like_Artist.objects.filter(
            user_id_id=request.user.id, artist_id_id=artist_id, like=True).delete()
    finally:
        return HttpResponseRedirect(reverse('home:artist', args=(artist_id,)))


def review(request, review_id=None):
    # Depends on receiving 'record_id' either from the POST or the Get (url)
    rev = get_object_or_404(Rating, pk=review_id) if review_id else None
    if not rev and request.GET.get("record_id"):
        rec_id = int(request.GET.get("record_id"))
        rev = Rating.objects.get(user_id_id=request.user.id, record_id_id=rec_id) if Rating.objects.filter(user_id_id=request.user.id, record_id_id=rec_id).count()>0 else None
    edit_mode = False if rev and rev.user_id.id != request.user.id else True
    if request.method == "POST":
        rec = get_object_or_404(Record, pk=request.POST.get("record_id"))
        if not rev and Rating.objects.filter(user_id_id=request.user.id, record_id=rec).count() == 0:
            rev = Rating.objects.create(user_id_id=request.user.id, record_id=rec,
                                        rating=request.POST.get("rating", None), review=request.POST.get("review", None))
        else:
            rev = rev or Rating.objects.get(user_id_id=request.user.id, record_id=rec)
            rev.rating = int(request.POST.get("rating", None))
            rev.review = request.POST.get("review", None)
            rev.save()
        return HttpResponseRedirect(reverse('home:record', args=(rec.pk,)))     
    else:
        record_id = rev.record_id.id if rev else request.GET.get("record_id")
        rec = get_object_or_404(Record, pk=record_id)
    tracks = discogs.get_record_master_by_id(rec.discogs_release_id).tracklist

    context = {
        "edit_mode": edit_mode,
        "review": rev,
        "record": rec,
        "tracks": tracks,
    }
    return render(request, "review.html", context=context)


def review_view(request, review_id):
    rev = get_object_or_404(Rating, pk=review_id)
    context = {
        "review": rev,
    }
    return render(request, "review_view.html", context=context)



def reviews(request):
    res = Rating.objects.filter(user_id_id=request.user.id)
    context = {"reviews": res, }
    return render(request, "reviews.html", context=context)


def artist(request, artist_id):
    like = False
    if request.user.is_authenticated:
        like = Like_Artist.objects.filter(user_id=request.user.id, artist_id_id=artist_id).count() > 0

    artist = get_object_or_404(Artist, id=artist_id)

    context = {'like': like, 'artist': artist}
    template = "artist.html"

    return render(request, template, context)


def record(request, record_id, collection_id=None):
    user_rating = None
    record_found_in = None
    if request.user.is_authenticated:
        if collection_id is not None:  # se user parte de colecção para lhe adicionar um record
            collection_to_add_to = collection_id
        try:
            user_rating = Rating.objects.get(
                user_id=request.user.id, record_id_id=record_id).rating
        except:
            user_rating = 0
        try:
            record_found_in = Collection_Record.objects.filter(record_id_id=record_id, collection_id__in=Collection.objects.filter(
                user_id=request.user.id))  # lista de nomes de coleções do user onde o record está    # TODO: testar
        except:
            record_found_in = []

    collection_to_add_to = collection_id
    record = get_object_or_404(Record, id=record_id)  # obtém objecto record
    discogs_record = discogs.get_record_master_by_id(record.discogs_release_id)
    tracks = discogs_record.tracklist
    videos = discogs_record.videos

    votes_count = Rating.objects.filter(record_id=record_id).count()
    avg_rating = Rating.objects.filter(record_id=record_id).aggregate(avg_rating=Avg('rating'))
    # convert to int (no half stars)
    avg_rating = int(avg_rating["avg_rating"]) if avg_rating["avg_rating"] else 0

    context = {'collection_to_add_to': collection_to_add_to,
               'user_rating': user_rating,
               'record_found_in': record_found_in,
               'record': record,
               'tracks': tracks,
               'videos': videos,
               'votes_count': votes_count,
               'avg_rating': avg_rating}
    template = 'record.html'

    return render(request, template_name=template, context=context)


def _is_super_user(user):
    return user.is_superuser


@user_passes_test(_is_super_user)
def staff_picks(request):
    picks = Staff_Picks.objects.all().order_by('-creation_date')
    paginator = Paginator(picks, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'staff_picks.html', {'page_obj': page_obj})
 
    
@login_required
def add_to_collection(request, record_id):
    user_collections = Collection.objects.filter(user_id = request.user)
    context = {'user_collections': user_collections, 'record_id': record_id}
    return render(request, "add_to_collection.html", context)


@user_passes_test(_is_super_user)
def staff_pick_edit(request, pick_id):
    sp = get_object_or_404(Staff_Picks, pk=pick_id)
    if request.method=="POST":
        if request.POST.get("title") and request.POST.get("recommendation"):
            sp.title=request.POST.get("title") 
            sp.recommendations=request.POST.get("recommendation")
            sp.save()
            return HttpResponseRedirect(reverse('home:staff_picks'))
    rec = sp.record
    votes_count = Rating.objects.filter(record_id=rec).count()
    avg_rating = Rating.objects.filter(record_id=rec).aggregate(avg_rating=Avg('rating'))
    # convert to int (no half stars)
    avg_rating = int(avg_rating["avg_rating"]) if avg_rating["avg_rating"] else 0
    tracks = discogs.get_record_master_by_id(rec.discogs_release_id).tracklist
    context = {
        "record": rec,
        "votes_count": votes_count,
        "avg_rating": avg_rating,
        "tracks": tracks,
        "pick": sp,
        }
    return render(request, 'staff_pick.html', context)


@user_passes_test(_is_super_user)
def staff_pick_add(request, record_id):
    rec = get_object_or_404(Record, pk=record_id)
    if request.method=="POST":
        if request.POST.get("title") and request.POST.get("recommendation"):
            sp = Staff_Picks.objects.create(user=request.user, record=rec, 
                    title=request.POST.get("title"), 

music_website/home/templates/add_to_collection.html
{% extends './base.html' %}
{% block content %}

<h1> Add record to collection </h1>
<br>

<h2>{{ error_message }}</h2>
<br>

<form method="POST" action = "{% url 'home:add_to_collection_save' record_id %}">
    {% csrf_token %}
    {% for collection in user_collections %}
    <div class="form-check">
        <input class="form-check-input" type="radio" name="collection", id="collection{{ forloop.counter }}" value="{{ collection.id }}" />
        <label class="form-check-label" for="collection{{ forloop.counter }}">
            {{collection.name}}
        </label>
    </div>
        <br>
    {% empty %}
    <p>You don't have any collections</p>
    <a href="{% url 'home:new_collection_form' user.username %}" class="btn btn-primary">Create a collection</a>
    {% endfor %}
    {% if user_collections%}<p><input class="btn btn-primary" type="submit" value="Add" /></p>{% endif %}
</form>


{% endblock %}

music_website/home/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
    <title>Music Collection</title>
  </head>
  <body>
    <!-- main container -->
    <div class="container mt-0">
      <!-- header -->
      <div class="row justify-content-center">
        <a class="col-6 g-0" href="{% url 'home:home_index' %}">
          <img class="col-6" src="{% static 'home/images/rgb_iscte_pt_horizontal_positive.png' %}">
        </a>
        <div class="col-2"></div>
        <div class="col-2">
          <hr class="mt-0 mb-4">
          <div>
            {% if user.is_authenticated %}
            <i class="bi bi-person"></i> Hello, {{ user.username }}!
            {% else %}
            <i class="bi bi-pencil-square"></i> <a href="{% url 'home:register' %}">Register</a>
            {% endif %}
          </div>
          <div>
            {% if user.is_authenticated %}
            <i class="bi bi-box-arrow-right"></i> <a href="{% url 'logout' %}">Logout</a>
            {% else %}
            <i class="bi bi-box-arrow-in-right"></i> <a href="{% url 'login' %}">Login</a>
            {% endif %}
          </div>
        </div>

      <!-- Navbar -->
      <div class="row justify-content-center">
      <nav class="navbar navbar-expand-lg navbar-light bg-light col-10">
        <div class="container-fluid">
          {% comment %} <a class="navbar-brand" href="#">Navbar</a> {% endcomment %}
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" aria-current="page" href="{% url 'home:home_index' %}">Home</a>
              <a class="nav-link" aria-current="page" href="{% url 'home:search' %}">Search</a>
      {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'home:mycollections' user.username %}">My Collections</a>
              <a class="nav-link" href="{% url 'home:reviews' %}">My Reviews</a>
              <a class="nav-link" href="{% url 'home:myartists' %}">My Artists</a>
              {% if user.is_superuser %}
              <a class="nav-link" href="{% url 'home:staff_picks' %}">Staff picks</a>
              {% endif %}
      {% endif %}      
            </div>
          </div>
        </div>
      </nav>
      </div>
      </div><!-- header end -->

      <!-- View -->
      <div class="row justify-content-center">
        <div class="col-10">
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div> 

    <div class="mt-0 mb-4 pt-8"></div><!--spacer-->

    <!-- Footer -->
    <footer class="bg-dark">
    <div class="container"><div class="row justify-content-center">
        <p class="small mt-2 mb-1 text-info col-8">Authors:  Catarina Castanheira |
                  João Martins |
                  Joel Paula
        </p>
        <p class="small mt-1 mb-3 text-info col-8">
          <a href="mailto:cccao@iscte-iul.pt" class="text-info">cccao@iscte-iul.pt</a> | 
          <a href="mailto:jdmms1@iscte-iul.pt" class="text-info">jdmms1@iscte-iul.pt</a> |
          <a href="mailto:jfrpa@iscte-iul.pt" class="text-info">jfrpa@iscte-iul.pt</a>
        </p>
    </div></div>
    </footer>

  </body>
</html>

music_website/home/templates/create_collection.html
{% extends './base.html' %}
{% block content %}

<h1> Create new collection </h1>
<br>

<h2>{{ error_message }}</h2>
<br>

<form method="POST" action = "{% url 'home:save_new_collection' user.username %}">
    {% csrf_token %}
    <div>
    <label for="collection_name">Collection name:</label>
    <input type="text" id="collection_name" name="collection_name" autofocus>
    </div>
    <br>
        <p>
            <input class="btn btn-primary" type="submit" value="Create">
        </p>

</form>


{% endblock %}

music_website/home/templates/delete_collection.html
{% extends './base.html' %}
{% block content %}

<h1> Remove collection from My Collections </h1>
<br>




{% endblock %}

music_website/home/templates/index.html
{% extends './base.html' %}
{% load static %}
{% block content %}
<h1>MCDb - Music Collection Database</h1>

<div class="row">
    <p class="lead">
        Discover more about the platform you didn't know you needed...
        All of your favorite artists and records just a few clicks away. 
        Register/Login in our platform to enjoy these funcionalities and many more!        
    </p>
</div>

<div class="row mb-4 mt-4">
    <div class="col-12">
        <a href="{% url 'home:search' %}"><span class="btn btn-primary btn-lg px-4 gap-3"> Search here</span></a> for you favorite artist or record...
    </div>
</div>

<!-- Home Lists -->
<div class="row mb-2 mt-2">
    <div class="col-4">
        {% include 'top_artists.html'%}
    </div>
    <div class="col-4">
        {% include 'top_records.html'%}
    </div>
    <div class="col-4">
        {% include 'top_staff_picks.html' %}
        {% include 'top_reviews.html'%}
    </div>
</div>

{% endblock %}

music_website/home/templates/my_artists.html
{% extends './base.html' %}
{% block content %}

<h1> My Artists </h1>
{% for artist in artists %}
<div class="card mb-3" style="max-width: 340px;">
  <div class="row g-0">
    <div class="col-md-4 pb-3">
      <img src="{{artist.picture_url}}" class="img-fluid rounded-start pb-3" alt="{{artist.name}}'s picture">
    </div>
    <div class="col-md-8">
      <div class="card-body" title="{{artist.bio}}">
        <a class="stretched-link" href="{% url 'home:artist' artist.id %}">
            <h6 class="card-title m-0 lh-sm">{{artist.name}}</h6>
        </a>
        <small class="card-text card-text position-absolute bottom-0 start-0 translate-middle-y ms-2 lh-sm" title="{{artist.likes}} people like this artist">
            <i class="bi bi-suit-heart-fill"></i> {{artist.likes}}</small>
        <p class="card-text">
        {% with artist.avg_rating|default_if_none:0 as avg_rating %}
        {% with ''|center:avg_rating as range %}
        {% for _ in range %}
            <i class="bi bi-star-fill" style="color: #fd7e14"></i>
        {% endfor %}
        {% endwith %}
        {% endwith %}
        {% if  artist.avg_rating %}<br><small class="text-muted lh-sm" style="font-size: xx-small;">(average rating from {{artist.review_count}} reviews)</small>{% endif %}
        </p>
      </div>
    </div>
  </div>
</div>
{% endfor %}

{% endblock %}

music_website/home/templates/reviews.html
{% extends './base.html' %}
{% block content %}
<h1>My Reviews</h1>

{% for review in reviews %}
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{review.record_id.cover_url}}" class="img-fluid rounded-start" alt="{{review.record_id.title}} record cover">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <span class="badge bg-light text-dark">{{review.record_id.artist_id.name}}</span>
        <h5 class="card-title">{{review.record_id.title}}</h5>
        <span class="badge rounded-pill bg-secondary">{{review.record_id.year}}</span>
        <span style="float: right;">
        {% with ''|center:review.rating as range %}
        {% for _ in range %}
            <i class="bi bi-star-fill" style="color: #fd7e14"></i>
        {% endfor %}
        {% endwith %}
        </span>
        <p class="card-text">{{review.review}}</p>
        <a class="btn btn-warning position-absolute bottom-0 end-0 mb-2 me-2" href="{% url 'home:review' review.pk %}">Edit</a>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}

music_website/home/templates/staff_picks.html
{% extends './base.html' %}
{% block content %}
<h1>Staff Picks</h1>

{% for pick in page_obj %}
<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{pick.record.cover_url}}" class="img-fluid rounded-start" alt="{{pick.record.title}} record cover">
    </div>
    <div class="col-md-8">
      <div class="card-body position-relative">
        <a href="{% url 'home:staff_pick_delete' pick.id %}" class="btn btn-sm bg-danger text-light position-absolute top-0 end-0 mt-2 me-2">delete</a>
        <span class="badge bg-light text-dark">{{pick.record.artist_id.name}}</span>
        <h5 class="card-title"><a href="{% url 'home:record' pick.record.id %}">{{pick.record.title}}</a></h5>
        <span class="badge rounded-pill bg-secondary me-2" style="float: left">{{pick.record.year}}</span>
        <p class="card-text">{{pick.title}}</p>
        <p class="card-text">{{pick.recommendations}}</p>
        <p class="card-text">
          <small class="text-muted fw-light lh-sm" style="font-size: xx-small;"><em>{{ pick.creation_date|date:"SHORT_DATETIME_FORMAT" }} by {{ pick.user.username }}</em></small>
          <a href="{% url 'home:staff_pick' pick.id %}" style="float:right">edit</a>
        </p>
      </div>
    </div>
  </div>
</div>
{% endfor %}

<nav aria-label="navigation on pages of staff picks">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            {% if page_obj.number != 1 %}<li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>{% endif %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
        {% endif %}

        <li class="page-item active" aria-current="page">
            <span class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
        </li>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
            {% if page_obj.number != page_obj.paginator.num_pages %}<li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>{% endif %}
        {% endif %}
    </ul>
</nav>

{% endblock %}

music_website/home/templates/top_reviews.html
<h2 class="badge bg-info text-dark">latest reviews</h2>
{% for review in top_reviews %}
<div class="card mb-3" style="max-width: 340px;">
  <div class="row g-0">
    <div class="col-md-4 pb-3">
      <img src="{{review.record_id.cover_url}}" class="img-fluid rounded-start pb-2" alt="{{review.record.title}}'s cover image">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <a class="stretched-link mt-0" href="{% url 'home:review_view' review.id %}">
          <h6 class="card-title m-0 lh-sm">{{review.record_id.title}}</h6>
        </a>
        <small class="card-text card-text position-absolute bottom-0 start-0 translate-middle-y ms-2 lh-sm">{{review.record_id.year}}</small>
        {% with ''|center:review.rating as range %}
        {% for _ in range %}
            <i class="bi bi-star-fill" style="color: #fd7e14"></i>
        {% endfor %}
        {% endwith %}
        <p class="card-text"><small class="text-muted lh-sm">{{review.record_id.artist_id.name}}</small></p>
        <p class="card-text text-truncate overflow-hidden" style="max-height: 3em;">
          <small class="lh-sm">{{review.review}}</small>
        </p>
        <p class="card-text">
          <small class="text-muted fw-light lh-sm" style="font-size: xx-small;"><em>by {{review.user_id.username}}</em></small></p>
      </div>
    </div>
  </div>
</div>
{% endfor %}

music_website/home/templates/top_staff_picks.html
<h2 class="badge bg-primary text-light">staff picks</h2>
{% for pick in staff_picks %}
<div class="card mb-3 border-primary" style="max-width: 340px;">
  <div class="row g-0">
    <div class="col-md-4 pb-3">
      <img src="{{pick.record.cover_url}}" class="img-fluid rounded-start pb-2" alt="{{pick.record.title}}'s cover image">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <a class="stretched-link mt-0" href="{% url 'home:staff_pick_view' pick.id %}">
          <h6 class="card-title m-0 lh-sm">{{pick.record.title}}</h6>
        </a>
        <small class="card-text card-text position-absolute bottom-0 start-0 translate-middle-y ms-2 lh-sm">{{pick.record.year}}</small>
        {% with pick.avg_rating|default_if_none:0 as avg_rating %}
        {% with ''|center:avg_rating as range %}
        {% for _ in range %}
            <i class="bi bi-star-fill" style="color: #fd7e14"></i>
        {% endfor %}
        {% endwith %}
        {% endwith %}
        <p class="card-text"><small class="text-muted lh-sm">{{pick.record.artist_id.name}}</small></p>
        <p class="card-text">
          <small class="text-muted fw-light lh-sm"><em>{{pick.title}}</em></small></p>
      </div>
        {% comment %} <p class="card-text text-truncate overflow-hidden" style="max-height: 3em;">
          <small class="lh-sm">{{pick.recommendations}}</small>
        </p> {% endcomment %}
    </div>
  </div>
</div>
{% endfor %}